### ISSUE TITLE
Throwing an uncaught type error if lib.js missing, rather than the supplied message

### ISSUE THREAD

**Issue by adrexia** [mateusz/silverstripe-frontend#11]
i.e. throws: Uncaught TypeError: Cannot read property 'addSearchParams' of undefined in this situation:

if (typeof $.path.addSearchParams==='undefined') {
    throw "ss.pagination error: please include framework/admin/javascript/lib.js";
}

Might need to check whether typeof $.path ==='undefined' before checking a sub property?

**Comment by mateusz** [comment]
Here you go https://github.com/mateusz/silverstripe-frontend/blob/master/javascript/jquery.ss.pagination.js#L118

**Comment by adrexia** [comment]
Thanks!
