### ISSUE TITLE
latest jquery.ss.pagination.js seems broken

### ISSUE THREAD

**Issue by ARNHOE** [mateusz/silverstripe-frontend#18]
```
$(document).ready(function(){
    $('div.pagination').sspagination({contentSelector: '.pagination-content'});
});
```

Chrome Debugger:
Uncaught SyntaxError: Unexpected token false

```
$('div.pagination').sspagination({contentSelector: '.pagination-content'});
```

I replaced the sspagination with this one, https://raw.github.com/mateusz/silverstripe-frontend/8b2a61f418c63f2f0bad63ad06f3da1f7168eeaa/javascript/jquery.ss.pagination.js and then it works.

**Comment by mateusz** [comment]
Fixed in https://github.com/mateusz/silverstripe-frontend/commit/32355af5d78c93fffae0a2151b8798c776f4ff30
