### ISSUE TITLE
New tagged release please

### ISSUE THREAD

**Issue by zarocknz** [mateusz/silverstripe-frontend#26]
Hi. Thanks for the module, we are using in our current project.

We have hit an issue with the pagination not displaying on iOS and see that you have fixed this some time ago (that popstate thing), however there has been no tagged release since then with the current stable version as 0.2, which does not have the fix.

Can you please do a new tagged release of this module?

Cheers,
DouG.

**Comment by mateusz** [comment]
Wow, that old unmanaged thing... Well, I've tagged it just for you :-) https://github.com/mateusz/silverstripe-frontend/releases/tag/0.3

**Comment by zarocknz** [comment]
Lol. Thanks man.
