### ISSUE TITLE
Example for a newb?

### ISSUE THREAD

**Issue by ARNHOE** [mateusz/silverstripe-frontend#9]
Hey,

I am trying to us the pagination plugin. But I cant seem to get it working, is there possiblity that you could make a more easy example? Which also includes the layout of the Pagination template?

I have been looking for a plugin like this for so long now, thanks for your work!

**Comment by mateusz** [comment]
Hi, here is some additional docs: https://github.com/mateusz/silverstripe-frontend/blob/more-docs/docs/sspagination-how-to.md .

If you could have a look and see if it's helpful and test it out that would be great!

If people use this plugin I might even start fixing the other issues ;-)

**Comment by ARNHOE** [comment]
It is working great in the limited time I have set it up. I will keep you up to date with any issues!

**Comment by mateusz** [comment]
Awesome :-)
